acemarProject/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView , LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView



urlpatterns = [

    path('admin/', admin.site.urls),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('users/', include('apps.users.urls', namespace="users")),
    path('quotes/', include('apps.quotes.urls', namespace="quotes")),
    path('accounts/login', LoginView.as_view(), {'template_name': 'index.html'}, name='login'),
    path('accounts/logout', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(),
         {'template_name': 'password_reset_form.html', 'email_template_name': 'password_reset_email.html'},
         name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(),
         {'template_name': 'password_reset_done.html', 'email_template_name': 'password_reset_done.html'},
         name = 'password_reset_done'),
    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(),
        {'template_name': 'password_reset_confirm.html'},
        name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(),
        {'template_name': 'password_reset_complete.html'},
        name = 'password_reset_complete'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)






# urlpatterns = [
#     # url(r'^$', include('apps.generalInfo.urls')),
#     url(r'^admin/', admin.site.urls),
#     url(r'^rest-auth/', include('rest_auth.urls')),
#     url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
#     url(r'^users/', include('apps.users.urls', namespace="users")),
#     url(r'^report/', include('apps.report.urls', namespace="report")),
#     # path('report', include('apps.report.urls')),
#     url(r'^accounts/login', login, {'template_name': 'index.html'}, name='login'),
#     url(r'^accounts/logout', logout_then_login, name='logout'),
#     url(r'^reset/password_reset', password_reset,
#         {'template_name': 'password_reset_form.html', 'email_template_name':'password_reset_email.html'},
#         name='password_reset'),
#     url(r'^reset/password_reset_done', password_reset_done,
#         {'template_name': 'password_reset_done.html', 'email_template_name':'password_reset_done.html'},
#         name='password_reset_done'),
#     url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
#         {'template_name': 'password_reset_confirm.html'},
#         name='password_reset_confirm'),
#     url(r'^reset/done', password_reset_complete,
#         {'template_name': 'password_reset_complete.html'},
#         name='password_reset_complete'),
#   #  url(r'^media/(?P<path>.*)$', static.serve,
#    #                       {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

#     #url(r'^$', include('apps.generalInfo.urls')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/quotes/urls.py
from django.conf.urls import url
# from django.urls import path
from .import views
from apps.quotes.views import quotesCreate, quotesDelete, quotesEdit, quotesList, quotesHome, quotesDetail

urlpatterns = [
    url(r'^create', quotesCreate.as_view(), name='quotesCreate'),
    url(r'^delete/(?P<pk>\d+)/', quotesDelete.as_view(), name='quotesDelete'),
    url(r'^edit/(?P<pk>\d+)/', quotesEdit.as_view(), name='quotesEdit'),
    url(r'^list', reportList.as_view(), name='quotesList'),
    url(r'^home', reportHome.as_view(), name='quotesHome'),
    url(r'^detail/(?P<pk>\d+)/$', quotesDetail.as_view(), name='quotesDetail'),



]

apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from apps.users.views import userCreate, userList, userDelete, userEdit, user_create, user_edit, user_list, user_delete

urlpatterns = [
    url(r'^create', userCreate.as_view(), name='usersCreate'),
    url(r'^delete/(?P<pk>\d+)/', permission_required('user.delete_profile')(userDelete.as_view()), name='usersDelete'),
    url(r'^edit/(?P<pk>\d+)/', permission_required('user.delete_profile')(userEdit.as_view()), name='usersEdit'),
    url(r'^list', permission_required('user.delete_profile')(userList.as_view()), name='usersList'),
    url(r'^fcreate/', user_create, name='user_create'),
    url(r'^flist/', permission_required('user.delete_profile')(user_list), name='user_list'),
    url(r'^fedit/(?P<pk>\d+)/', permission_required('user.delete_profile')(user_edit), name='user_edit'),
    url(r'^fdelete/(?P<pk>\d+)/', permission_required('user.delete_profile')(user_delete), name='user_delete'),
]

apps/quotes/models.py
from django.db import models

# Create your models here.

class Quotes(models.Model):
    name = models.CharField(max_length=50)
    phone = models.PositiveSmallIntegerField(null=True)
    mail = models.EmailField(null=True)
    typematerial = models.CharField(max_length=50, null=True)
    description = models.TextField()



    def __str__(self):
        texto = "{0}"
        return texto.format(self.name)

apps/quotes/views.py
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.contrib import messages
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.core.urlresolvers import reverse_lazy
from apps.quotes.forms import quotesForm
from apps.quotes.models import Quotes


# Create your views here.

class quotesCreate(CreateView):
    model = Quotes
    template_name = "quotesForm.html"
    form_class = quotesForm
   # second_form_class = profileForm
    success_url = reverse_lazy('quotes:quotesList')

class quotesDelete(ListView):
    model = Quotes
    template_name = "quotesDelete.html"
    success_url = reverse_lazy('quotes:quotesList')

class quotesEdit(UpdateView):
    model = Quotes
    template_name = "quotesForm.html"
    form_class = quotesForm
    success_url = reverse_lazy('quotes:quotesList')

class quotesList(ListView):
    model = Quotes
    template_name="quotesList.html"

class quotesHome(ListView):
    model = Quotes
    template_name="quotesHome.html"



class quotesDetail(DetailView):
    model = Quotes
    template_name = "quotesDetail.html"
    # form_class = quotesForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print ("pk", self.kwargs['pk'])
        # Quotes.objects.create(
        #     quotes_id = self.kwargs['pk'],
        #     quotes_id = self.request.users.id
        # )
        return context

apps/quotes/templates/quotesDelete.html
{% extends 'layouts/base.html' %}

{% block contenttitle %}
Está seguro que desea eliminar esta cotización: {{ object.first_name }}?
{%endblock%}

{% block contendbody %}

<form method="post">
    {% csrf_token %}
    <a href="#" ><button class="button special" name="Eliminar" type="submit" >Si, Eliminar</button></a>
    <a class="button" href="{% url 'quotes:quotesList' %}">Cancelar</a>
</form>
{% endblock %}

apps/quotes/templates/quotesDetail.html
{% extends 'layouts/base.html' %}

{% block title %}
Detalles de Cotizaciones del sistema
{%endblock%}

{% block bodyClass %}detail{% endblock %}

{% block contendbody %}
<!-- TODO: move this styles to "base" -->
<style>
  .wrapper-content {
    padding-left: 4rem;
    padding-right: 0;
  }

  .content {
    background: #fff;
    padding: 2rem;
    /* margin: 25px; */
    border-radius: 0 0 0 4rem;
    min-height: calc(100vh - 4rem);
    box-shadow: 0 16px 38px -12px rgb(0 0 0 / 56%), 0 4px 25px 0px rgb(0 0 0 / 12%), 0 8px 10px -5px rgb(0 0 0 / 20%);
  }

  .report-cover img {
    border: 5px solid #08345b;
    border-radius: 1.5rem;
    object-fit: cover;
  }

  .btn-circle {
    width: 64px;
    height: 64px;
    /* padding: 10px 16px; */
    border-radius: 64px;
    font-size: 24px;
    line-height: 74px;
  }

  .btn-circle>.material-icons-round {
    font-size: 36px;
  }

  .btn-support {
    position: fixed;
    z-index: 9999;
    right: 10px;
    bottom: 10px;
    line-height: 70px;
    box-shadow: 0 16px 38px -12px rgb(0 0 0 / 56%), 0 4px 25px 0px rgb(0 0 0 / 12%), 0 8px 10px -5px rgb(0 0 0 / 20%);
    background: #f1f1f1;
  }
</style>
<nav class="navbar navbar-light navbar-users bg-light mb-5">
  <div class="container">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'quotes:quotesHome'%}">Inicio</a>
      </li>
      {% if user.is_staff %}
      <li class="nav-item"><a href="{% url 'quotes:quotesList'%}" class="nav-link">Cotizaciónes</a></li>
      <li class="nav-item"><a href="{% url 'users:users_list'%}" class="nav-link" aria-current="page">Usuarios</a></li>
      {% endif %}
    </ul>

    <a class="navbar-brand" href="#">
      <img src="https://graduados.poligran.edu.co/static/img/logo-poli-vertical.png" alt="" width="156">
    </a>
  </div>
</nav>
<main>
  <div class="container pt-5">
    <div class="row">
      <div class="col-12">
        <div class="card card-user mx-auto">
          <div class="card-body">
            <div class="row align-items-center">
              <div class="col-auto">
                <div class="report-cover">
                  <img src="/media/{{object.imageReport}}" width="400" height="400">
                </div>
              </div>
              <div class="col">
                <div class="card border-0 py-5">
                  <div class="card-body">
                    <h2 class="mb-0" style="color: #08345b;">{{object.name}}</h2>
                    <h5 style="color: #35aed7;">Fecha de Creacion: 12/05/2022</h5>
                    <p>{{object.description}}</p>
                  </div>
                  <div class="card-footer">
                    <div class="row align-items-center">
                      <div class="col-auto">
                        <!-- <a href="/media/{{object.fileReport}}" class="btn btn-primary btn-lg">Solicitud de acceso</a> -->
                        <a href="/media/{{object.fileReport}}" class="btn btn-primary btn-lg">Ver reporte</a>
                      </div>
                      <div class="col-auto">
                        <button class="btn btn-lg">
                          Video Explicativo
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</main>


<a href="#" class="btn btn-light btn-circle btn-support">
  <span class="material-icons-round">support</span>
</a>
{% endblock %}

apps/quotes/templates/quotesForm.html
{% extends 'layouts/base.html' %}
{%block title%}
Cotizaciones del Sistema
{%endblock%}
{% block bodyClass %}report{% endblock %}

{% block contendbody %}
<style>
  .form-floating>textarea.form-control {
    height: auto;
  }

  .form-floating--file {
    padding: 1rem 0.75rem 0.625rem;
    background: #08345b;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
  }

  .form-floating--file input {
    border: none;
  }

  .form-floating--file label {
    opacity: .65;
    transform: scale(.85) translateY(-0.5rem) translateX(-0.85rem);
  }

  #id_levels {
    /* height: calc(3.5rem + 2px); */
    line-height: 1.25;
    display: block;
    width: 100%;
    padding: 2.25rem 0.75rem 0.625rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #fff;
    /* color: #212529; */
    background-color: #08345b;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border-radius: 0.25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  }

  #id_levels li {
    display: block;
    min-height: 1.5rem;
    padding-left: 1.5em;
    margin-bottom: 0.125rem;
  }

  #id_levels + label {
    transform: scale(.85) translateY(-0.5rem) translateX(0.15rem);
  }

  #id_fileType {
    background: #f9a801;
  }
</style>
<nav class="navbar navbar-light navbar-report">
  <div class="container">
    <a href="{% url 'quotes:quotesList'%}" class="btn">
      <div class="d-flex">
        <span class="material-icons-round me-2">arrow_back</span> Lista de Cotizaciones
      </div>
    </a>
    <a class="navbar-brand" href="#">
      <img src="https://graduados.poligran.edu.co/static/img/logo-poli-vertical.png" alt="" height="64px">
    </a>
  </div>
</nav>
<main class="form-report mx-auto">
  <form method="post" enctype="multipart/form-data" class="card card-report mx-auto">
    {% csrf_token %}
    <div class="card-body row2 mx-0">
      <!-- <div class="col-6"> -->
        {% for field in form %}
          <div class="form-wrapper mb-3">
            <div class="form-floating">
              {{ field.errors }}
              {{ field }}
              {{ field.label_tag }}
            </div>
          </div>
        {% endfor %}
      <!-- </div> -->
    </div>

    <div class="card-footer">
      <div class="text-center">
        <button class="btn btn-lg btn-primary" type="submit">Crear Cotización</button>
      </div>
    </div>
  </form>
</main>
<!-- <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="guardar" class="button special" type="submit" >Guardar</button>
    <a href="{% url 'report:reportList' %}"><button name="regresar" class="button" type="button" >regresar</button></a>
</form> -->
{% endblock%}

{% block customJs %}
<script>
  $('#id_imageReport, #id_fileReport').parent('.form-floating').addClass('form-floating--file');
  $('.js-typeInput').parents('.form-wrapper').hide();
  $('#id_fileType').change(function() {
    $('.js-typeInput').parents('.form-wrapper').hide();
    console.log('>>>', $(this).val())

    if ($(this).val() == '4'){
      $('#id_sqlData').parents('.form-wrapper').show();
    }

    if ($(this).val() == '5'){
      $('#id_biData').parents('.form-wrapper').show();
    }

    if ($(this).val() == '1' || $(this).val() == '2' || $(this).val() == '3') {
      $('#id_fileReport').parents('.form-wrapper').show();
    }
  });
  // $('#id_biData')
  // $('#id_sqlData')
  // $('#id_password1, #id_password2').addClass('form-control');
</script>
{% endblock%}

apps/quotes/templates/quotesHome.html
{% extends 'layouts/base.html' %}

{% block title %}
Listado de cotizaciones del sistema
{%endblock%}

{% block contendbody %}
<style>
  body {
    background: #08345b;
  }

  .wrapper-content {
    padding-left: 4rem;
    padding-right: 0;
  }

  .content {
    background: #fff;
    padding: 2rem;
    /* margin: 25px; */
    border-radius: 0 0 0 4rem;
    min-height: calc(100vh - 4rem);
    box-shadow: 0 16px 38px -12px rgb(0 0 0 / 56%), 0 4px 25px 0px rgb(0 0 0 / 12%), 0 8px 10px -5px rgb(0 0 0 / 20%);
  }

  /*
 * Sidebar
 */

  .sidebar {
    position: fixed;
    top: 0;
    /* rtl:raw:
  right: 0;
  */
    bottom: 0;
    /* rtl:remove */
    left: 0;
    z-index: 100;
    /* Behind the navbar */
    padding: 2rem 0 0;
    /* Height of navbar */
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
  }

  @media (max-width: 767.98px) {
    .sidebar {
      top: 5rem;
    }
  }

  .sidebar-sticky {
    position: relative;
    top: 0;
    height: calc(100vh - 48px);
    padding-top: .5rem;
    overflow-x: hidden;
    overflow-y: auto;
    /* Scrollable contents if viewport is shorter than content. */
  }

  .sidebar .nav-link {
    font-weight: 500;
    color: #08345b;
    background: #fff;
    border-radius: 0.75rem;
    padding: .75rem 1rem;
  }

  .sidebar .nav-link .feather {
    margin-right: 4px;
    color: #727272;
  }

  .sidebar .nav-link.active {
    color: #2470dc;
  }

  .sidebar .nav-link:hover .feather,
  .sidebar .nav-link.active .feather {
    color: inherit;
  }

  .sidebar-heading {
    font-size: .75rem;
    text-transform: uppercase;
  }

  .home-card {
    overflow: hidden;
    border-radius: 0 3rem 3rem 3rem;
  }

  .col-12.col-md-4.p-4:nth-child(1) .home-card {
    background: #f40b7b;
  }

  .col-12.col-md-4.p-4:nth-child(2) .home-card {
    background: #8ac61c;
  }

  .home-card-image {
    object-fit: cover;
    border-radius: 0 50% 50%;
    margin: -15% -15%;
  }

  .home-card-content {
    margin-top: -15%;
  }

  .home-card-content h3 {
    color: #fff;
    font-weight: 800;
  }

  .btn-circle {
    width: 64px;
    height: 64px;
    /* padding: 10px 16px; */
    border-radius: 64px;
    font-size: 24px;
    line-height: 74px;
  }

  .btn-circle>.material-icons-round {
    font-size: 36px;
  }

  .btn-support {
    position: fixed;
    z-index: 9999;
    right: 10px;
    bottom: 10px;
    line-height: 70px;
    box-shadow: 0 16px 38px -12px rgb(0 0 0 / 56%), 0 4px 25px 0px rgb(0 0 0 / 12%), 0 8px 10px -5px rgb(0 0 0 / 20%);
    background: #f1f1f1;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 sidebar">
      <div class="position-sticky ps-4">
        <ul class="nav flex-column">
          <li class="nav-item mb-4">
            <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
              <input type="checkbox" class="btn-check" id="btncheck1" autocomplete="off">
              <label class="btn btn-outline-warning" for="btncheck1">Inicio</label>

              <input type="checkbox" class="btn-check" id="btncheck2" autocomplete="off" checked>
              <label class="btn btn-outline-warning" for="btncheck2">Cotizaciones</label>
            </div>
          </li>
          <li class="nav-item mb-4">
            <a class="nav-link active" aria-current="page" href="#">
              <div class="d-flex">
                <span class="material-icons-round me-3">
                  auto_stories
                </span>
                Texto Aqui
              </div>
            </a>
          </li>
          <li class="nav-item mb-4">
            <a class="nav-link" href="#">
              <div class="d-flex">
                <span class="material-icons-round me-3">
                  sentiment_very_satisfied
                </span>
                Texto Aqui
              </div>
            </a>
          </li>
          <li class="nav-item mb-4">
            <a class="nav-link" href="#">
              <div class="d-flex">
                <span class="material-icons-round me-3">
                  laptop_chromebook
                </span>
                Texto Aqui
              </div>
            </a>
          </li>
          <li class="nav-item mb-4">
            <a class="nav-link" href="#">
              <div class="d-flex">
                <span class="material-icons-round me-3">
                  calculate
                </span>
                Texto Aqui
              </div>
            </a>
          </li>
          <li class="nav-item mb-4">
            <a class="nav-link" href="#">
              <div class="d-flex">
                <span class="material-icons-round me-3">
                  extension
                </span>
                Texto Aqui
              </div>
            </a>
          </li>
          <li class="nav-item mb-4">
            <a class="nav-link" href="#">
              <div class="d-flex">
                <span class="material-icons-round me-3">
                  psychology
                </span>
                Texto Aqui
              </div>
            </a>
          </li>
          <li class="nav-item mb-4">
            <a class="nav-link" href="#">
              <div class="d-flex">
                <span class="material-icons-round me-3">
                  keyboard
                </span>
                Texto Aqui
              </div>
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="wrapper-content col-md-9 ms-sm-auto col-lg-10">
      <div class="content">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
          <div class="input-group">
            <input type="text" class="form-control" id="name" placeholder="Buscar reporte" name="search"
              aria-label="Username" aria-describedby="basic-addon1" style="background: #dedede;">
            <span class="input-group-text" id="basic-addon1" style="background: #dedede;">
              <button type="submit" class="btn btn-primary" style="background:#08345b">Buscar</button>
              <!-- <span class="material-icons-round">
                search
              </span> -->
            </span>
          </div>
        </div>
        <!-- <div class="col-4 mb-3">
          <select id="id_categories" class="form-control" name="categories">
            <option selected disabled>Filtrar por Categoria</option>
            {% for choice in categories %}
            <option value="{{ choice.id }}" data-time="{{ choice.time }}">{{ choice.name }}</option>
            {% endfor %}
          </select>
        </div> -->

        <div class="row">
          {% if object_list %}
          {% for app in object_list %}
          <div class="col-12 col-md-4 p-4">
            <a href="{% url 'quotes:quotesDetail' app.id %}" class="text-decoration-none">
              <div class="card home-card p-2">
                <div class="ratio ratio-1x1">
                  <img src="/media/{{app.imageReport}}" class="home-card-image">
                </div>
                <div class="home-card-content card-body row align-items-center">
                  <div class="col-auto">
                    <button class="btn btn-light btn-circle">
                      <span class="material-icons-round">Download</span>
                    </button>
                  </div>
                  <div class="col text-end">
                    <h5 class="card-title font-weight-bold text-white">{{app.name}}</h5>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
          {%endif%}
        </div>
      </div>
    </main>
  </div>

  <a href="#" class="btn btn-light btn-circle btn-support">
    <span class="material-icons-round">Support</span>
  </a>
</div>
{% endblock %}

{% block customJs %}
<!-- <script>
  $('.home-card').each(function () {
    var back = ["#f40b7b", "#8ac61c", "#f9a900", "#39b7c8"];
    var rand = back[Math.floor(Math.random() * back.length)];
    $(this).css('background', rand);
  });
</script> -->
{% endblock %}

apps/quotes/templates/quotesList.html
{% extends 'layouts/base.html' %}

{% block title %}
Listado de cotizaciones del sistema
{%endblock%}

{% block contendbody %}
<style>
  thead {
    background: #0f375a;
  }

  thead th {
    color: #fff;
  }
</style>
<nav class="navbar navbar-light navbar-users">
  <div class="container">
    {% if user.is_staff %}
    <!-- <nav>
        <a href="{% url 'users:user_list'%}">listado usuarios menu</a>
      </nav> -->
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{% url 'quotes:quotesList'%}" class="nav-link active">Cotizaciones</a></li>
      <li class="nav-item"><a href="{% url 'users:user_list'%}" class="nav-link" aria-current="page">Usuarios</a></li>
    </ul>
    {% endif %}

    <!-- {% if user.get_username %}
    <h1>if logged</h1>
    {% endif %} -->

    <a class="navbar-brand" href="#">
      <img src="https://graduados.poligran.edu.co/static/img/logo-poli-vertical.png" alt="" width="156">
    </a>
  </div>
</nav>
<main>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="card card-user mx-auto">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th></th>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <!-- <th>Embebido Power</th> -->
                    <!-- <th>Codigo Sql</th> -->
                    <th>Texto</th>
                    <th>Tipo de reporte</th>
                    <th>Nivel</th>
                    <th>Archivo</th>
                    <th class="text-center">Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% if object_list %}
                  {% for app in object_list %}
                  <tr>
                    <td>
                      <img src="/media/{{app.imageReport}}" class="rounded" width="64" height="64">
                    </td>
                    <td>{{app.name}}</td>
                    <td>{{app.description}}</td>
                    <!-- <td>{{app.biData}}</td> -->
                    <!-- <td>{{app.sqlData}}</td> -->
                    <td>{{app.text}}</td>
                    <td>{{app.fileType}}</td>
                    <td>
                      <ul>
                        {% for l in app.levels.all %}
                          <li>
                            {{l}}
                          </li>
                        {% endfor %}
                      </ul>
                    </td>
                    <td>
                      <a href="/media/{{app.fileReport}}">Descargar</a>
                    </td>

                    <td class="text-center">
                      <a href="{% url 'quotes:quotesEdit' app.id %}">Editar</a> /
                      <a href="{% url 'quotes:quotesDelete' app.id %}">Eliminar</a>
                    </td>
                  </tr>
                  {% endfor %}
                  {%else%}
                  <tr>
                    <td colspan="8">
                      <h1>No Existen Cotizaciones Creadas</h1>
                    </td>
                  </tr>
                  {%endif%}
                </tbody>
              </table>
            </div>
          </div>

          <div class="card-footer">
            <div class="text-end">
              <a class="btn btn-lg btn-primary" href="{% url 'quotes:quotesCreate'%}">Crear Cotizaciones</a>
            </div>
          </div>
        </div>
      </div>
</main>
{% endblock %}