acemarProject/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView , LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView



urlpatterns = [

    path('admin/', admin.site.urls),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('users/', include('apps.users.urls', namespace="users")),
    path('quotes/', include('apps.quotes.urls', namespace="quotes")),
    path('accounts/login', LoginView.as_view(), {'template_name': 'index.html'}, name='login'),
    path('accounts/logout', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(),
         {'template_name': 'password_reset_form.html', 'email_template_name': 'password_reset_email.html'},
         name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(),
         {'template_name': 'password_reset_done.html', 'email_template_name': 'password_reset_done.html'},
         name = 'password_reset_done'),
    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(),
        {'template_name': 'password_reset_confirm.html'},
        name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(),
        {'template_name': 'password_reset_complete.html'},
        name = 'password_reset_complete'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)






# urlpatterns = [
#     # url(r'^$', include('apps.generalInfo.urls')),
#     url(r'^admin/', admin.site.urls),
#     url(r'^rest-auth/', include('rest_auth.urls')),
#     url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
#     url(r'^users/', include('apps.users.urls', namespace="users")),
#     url(r'^report/', include('apps.report.urls', namespace="report")),
#     # path('report', include('apps.report.urls')),
#     url(r'^accounts/login', login, {'template_name': 'index.html'}, name='login'),
#     url(r'^accounts/logout', logout_then_login, name='logout'),
#     url(r'^reset/password_reset', password_reset,
#         {'template_name': 'password_reset_form.html', 'email_template_name':'password_reset_email.html'},
#         name='password_reset'),
#     url(r'^reset/password_reset_done', password_reset_done,
#         {'template_name': 'password_reset_done.html', 'email_template_name':'password_reset_done.html'},
#         name='password_reset_done'),
#     url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
#         {'template_name': 'password_reset_confirm.html'},
#         name='password_reset_confirm'),
#     url(r'^reset/done', password_reset_complete,
#         {'template_name': 'password_reset_complete.html'},
#         name='password_reset_complete'),
#   #  url(r'^media/(?P<path>.*)$', static.serve,
#    #                       {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

#     #url(r'^$', include('apps.generalInfo.urls')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/quotes/urls.py
from django.conf.urls import url
# from django.urls import path
from .import views
from apps.quotes.views import quotesCreate, quotesDelete, quotesEdit, quotesList, quotesHome, quotesDetail

urlpatterns = [
    url(r'^create', quotesCreate.as_view(), name='quotesCreate'),
    url(r'^delete/(?P<pk>\d+)/', quotesDelete.as_view(), name='quotesDelete'),
    url(r'^edit/(?P<pk>\d+)/', quotesEdit.as_view(), name='quotesEdit'),
    url(r'^list', reportList.as_view(), name='quotesList'),
    url(r'^home', reportHome.as_view(), name='quotesHome'),
    url(r'^detail/(?P<pk>\d+)/$', quotesDetail.as_view(), name='quotesDetail'),



]

apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from apps.users.views import userCreate, userList, userDelete, userEdit, user_create, user_edit, user_list, user_delete

urlpatterns = [
    url(r'^create', userCreate.as_view(), name='usersCreate'),
    url(r'^delete/(?P<pk>\d+)/', permission_required('user.delete_profile')(userDelete.as_view()), name='usersDelete'),
    url(r'^edit/(?P<pk>\d+)/', permission_required('user.delete_profile')(userEdit.as_view()), name='usersEdit'),
    url(r'^list', permission_required('user.delete_profile')(userList.as_view()), name='usersList'),
    url(r'^fcreate/', user_create, name='user_create'),
    url(r'^flist/', permission_required('user.delete_profile')(user_list), name='user_list'),
    url(r'^fedit/(?P<pk>\d+)/', permission_required('user.delete_profile')(user_edit), name='user_edit'),
    url(r'^fdelete/(?P<pk>\d+)/', permission_required('user.delete_profile')(user_delete), name='user_delete'),
]

apps/users/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from rest_framework.authtoken.models import Token
from django.conf import settings
from django.contrib.auth.models import User
# from apps.report.models import Report

# Create your models here.

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()


# class Levels(models.Model):
#     name = models.CharField(max_length=30, blank=True)
#     def __str__(self): return self.name



# class ReportType(models.Model):
#     name = models.CharField(max_length=50, null=True)

#     def __str__(self):
#         texto = "{0}"
#         return texto.format(self.name)

# class Categories(models.Model):
#     name = models.CharField(max_length=50, null=True)

#     def __str__(self):
#         texto = "{0}"
#         return texto.format(self.name)


# class Report(models.Model):
#     name = models.CharField(max_length=50, null=True)
#     biData = models.CharField(max_length=50, null=True)
#     sqlData = models.CharField(max_length=50, null=True)
#     description = models.TextField(null=True)
#     text = models.CharField(max_length=50, null=True)
#     fileType = models.ForeignKey(ReportType, on_delete=models.SET_NULL, null=True)
#     levels = models.ManyToManyField(Levels)
#     fileReport = models.FileField(upload_to="reportFiles", null=True)
#     imageReport = models.ImageField(upload_to="reportImage",null=True)
#     viewsReport = models.IntegerField(null=True)
#     uses = models.IntegerField(null=True)
#     categories = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True)


#     def __str__(self):
#         texto = "{0}"
#         return texto.format(self.name)




class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    phone = models.CharField(max_length=30, blank=True)
    nationalId = models.CharField(max_length=30, null=True, blank=True)
    deviceId = models.CharField(max_length=500, blank=True)
    # levels = models.ForeignKey(Levels, on_delete=models.SET_NULL, null=True)
    # singleLevels = models.ManyToManyField(Report)

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm
from apps.users.models import Profile

class userForm(UserCreationForm):
    group = forms.ModelChoiceField(queryset=Group.objects.all(), required=True)

    class Meta:
        model=User
        fields=[
            'username',
            'first_name',
            'last_name',
            'email',
            'group',
            'password1',
            'password2',
            # 'levels',
        ]
        labels = {
            'username': 'Usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'email': 'Correo Electrónico',
            'group': 'Grupo',
            'password1': 'Contraseña',
            'password2': 'Confirmar Contraseña',
            # 'levels': 'Niveles',
            }
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
            'group': forms.Select(attrs={'class':'form-select'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Again'}),
            # 'levels': forms.Select(
            #     attrs={
            #         'class': 'form-select',
            #         'placeholder': 'Niveles'
            #         }
            #     ),
        }

class profileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=[
            'phone',
            'levels',
            'singleLevels',
        ]
        labels = {
            'phone': 'Telefono',
            'levels': 'Niveles',
            'singleLevels': 'Nivel individual',
            }
        widgets = {
            'phone': forms.TextInput(attrs={'class':'form-control'}),
            'levels': forms.Select(
                attrs={
                    'class': 'form-select',
                    'placeholder': 'Niveles'
                    }
                ),
            'singleLevels': forms.CheckboxSelectMultiple(),
        }

apps/users/views.py
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from apps.users.forms import userForm, profileForm
from apps.users.models import Profile

# Create your views here.

class userCreate(CreateView):
    model=User
    template_name="usersForm.html"
    form_class=userForm
   # second_form_class = profileForm
    success_url=reverse_lazy('users:usersList')

class userDelete(ListView):
    model = User
    template_name = "usersDelete.html"
    success_url = reverse_lazy('users:usersList')

class userEdit(UpdateView):
    model = User
    template_name = "usersForm.html"
    form_class = userForm
    success_url = reverse_lazy('users:usersList')

class userList(ListView):
    model=User
    template_name="UsersList.html"

def user_create(request):
    if request.method == 'POST':
        form = userForm(request.POST, request.FILES)
        form2 = profileForm(request.POST, request.FILES)
        if form.is_valid() and form2.is_valid():
            #form.groups.add(form.cleaned_data['group'])
            user = form.save()
            # in case you need to assign a new group without admin permision
            #user.groups.add(form.cleaned_data['group'])
            profile = form2.save(commit=False)
            #form2.save()
            profile.user_id = user.id
            profile.save()
            return redirect('users:user_list')
    else:
        form = userForm()
        form2 = profileForm()
    return render(request, 'usersForm.html', {'form': form, 'form2': form2})

def user_list(request):
    userList = User.objects.all().order_by('id')
    contexto = {'object_list': userList}
    return render(request, 'users_list.html', contexto)
    #return render(request, 'appointment_list.html', {'appointments', 'test'})
    #return render_to_response("appointment_list.html", {'appointments', applist}, RequestContext(request))

def user_edit(request, pk):
    user = User.objects.get(id=pk)
    profile = Profile.objects.get(user=user)
    if request.method == 'GET':
        form=userForm(instance=user)
        form2=profileForm(instance=user.profile)
    else:
        form = userForm(request.POST, instance=user)
        form2 = profileForm(request.POST, instance=user.profile)
        if form.is_valid() and form2.is_valid():
            user = form.save()
            user.groups.clear()
            user.groups.add(form.cleaned_data['group'])
            form2.save()
        return redirect('users:user_list')
    return render(request, 'users_form.html', {'form': form, 'form2': form2})

def user_delete(request, pk):
    user=User.objects.get(id=pk)
    if request.method=='POST':
        user.delete()
        return redirect('users:user_list')
    return render(request, 'users_delete.html', {'user': user})

apps/users/templates/UsersList.html
{% extends 'layouts/base.html' %}

{% block title %}
Listado de usuarios del sistema
{%endblock%}

{% block contendbody %}
<style>
  thead {
    background: #0f375a;
  }

  thead th {
    color: #fff;
  }
</style>
<nav class="navbar navbar-light navbar-users">
  <div class="container">
    {% if user.is_staff %}
    <!-- <nav>
        <a href="{% url 'users:user_list'%}">listado usuarios menu</a>
      </nav> -->
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{% url 'quotes:quotesList'%}" class="nav-link">Cotizaciones</a></li>
      <li class="nav-item"><a href="{% url 'users:user_list'%}" class="nav-link active" aria-current="page">Usuarios</a></li>
    </ul>
    {% endif %}

    <!-- {% if user.get_username %}
    <h1>if logged</h1>
    {% endif %} -->

    <a class="navbar-brand" href="#">
      <img src="https://graduados.poligran.edu.co/static/img/logo-poli-vertical.png" alt="" width="156">
    </a>
  </div>
</nav>
<main>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="card card-user mx-auto">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th>Nivel de acceso</th>
                    <th>Nombre de usuario</th>
                    <th>Identificacion</th>
                    <th>Nombres</th>
                    <!-- <th>Apellidos</th> -->
                    <!-- <th>Correo electronico</th> -->
                    <th class="text-center">Opciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% if object_list %}
                  {% for app in object_list %}
                  <tr>
                    <th>{{app.profile.levels}}</th>
                    <td>{{app.username}}</td>
                    <td>{{app.documentation}}</td>
                    <td>{{app.first_name}} {{app.last_name}}</td>
                    <!-- <td>{{app.email}}</td> -->
                    <td class="text-center"><a href="{% url 'users:usersEdit' app.id %}">Editar</a> /
                      <a href="{% url 'users:usersDelete' app.id %}">Eliminar</a>
                    </td>
                  </tr>
                  {% endfor %}
                  {%else%}
                  <tr>
                    <td colspan="8">
                      <h1>No existen los registros de usuarios</h1>
                    </td>
                  </tr>
                  {%endif%}
                </tbody>
              </table>
            </div>
          </div>

          <div class="card-footer">
            <div class="text-end">
              <a class="btn btn-lg btn-primary" href="{% url 'users:usersCreate'%}">Crear usuario</a>
            </div>
          </div>
        </div>
      </div>
</main>
{% endblock %}

apps/users/templates/usersDelete.html
{% extends 'layouts/base.html' %}

{% block contenttitle %}
Está seguro que desea eliminar el Usuario: {{ object.first_name }}?
{%endblock%}

{% block contendbody %}

<form method="post">
    {% csrf_token %}
    <a href="#" ><button class="button special" name="Eliminar" type="submit" >Si, Eliminar</button></a>
    <a class="button" href="{% url 'users:usersList' %}">Cancelar</a>
</form>
{% endblock %}

apps/users/templates/usersForm.html
{% extends 'layouts/base.html' %}

{% block title %}Crear usuario{% endblock %}
{% block bodyClass %}user{% endblock %}

{% block contendbody %}
<style>
  #id_singleLevels {
    /* height: calc(3.5rem + 2px); */
    line-height: 1.25;
    display: block;
    width: 100%;
    padding: 2.25rem 0.75rem 0.625rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #fff;
    /* color: #212529; */
    /* background-color: #fff; */
    background-clip: padding-box;
    border: 1px solid #ced4da;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border-radius: 0.25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  }

  #id_singleLevels li {
    display: block;
    min-height: 1.5rem;
    padding-left: 1.5em;
    margin-bottom: 0.125rem;
  }

  #id_singleLevels + label {
    transform: scale(.85) translateY(-0.5rem) translateX(0.15rem);
  }
</style>
<div class="user-decorator"></div>
<nav class="navbar navbar-light navbar-user">
  <div class="container">
    <a href="{% url 'users:usersList'%}" class="btn">
      <div class="d-flex">
        <span class="material-icons-round me-2">arrow_back</span> Lista de usuarios
      </div>
    </a>
    <a class="navbar-brand" href="#">
      <img src="https://www.poli.edu.co/sites/default/files/logos/logo_poli_nuevo_footer-ver5.png" alt="" height="64px">
    </a>
  </div>
</nav>
<main class="form-user mx-auto">
  <form method="post" class="card card-user mx-auto">
    {% csrf_token %}
    <div class="card-body">
      {% for field in form %}
      <div class="mb-3">
        <div class="form-floating">
          {{ field.errors }}
          {{ field }}
          {{ field.label_tag }}
        </div>
      </div>
      {% endfor %}
      {% for field in form2 %}
      <div class="mb-3">
        <div class="form-floating">
          {{ field.errors }}
          {{ field }}
          {{ field.label_tag }}
        </div>
      </div>
      {% endfor %}
    </div>

    <div class="card-footer">
      <div class="text-center">
        <button class="btn btn-lg btn-primary" type="submit">Crear usuario</button>
      </div>
    </div>
  </form>
</main>
{% endblock%}

{% block customJs %}
<script>
  $('#id_group').addClass('form-select');
  $('#id_password1, #id_password2').addClass('form-control');
</script>
{% endblock %}

apps/users/templates/users_delete.html
{% extends 'layouts/base.html' %}

{% block contenttitle %}
Está seguro que desea eliminar el Usuario: {{ object.first_name }}?
{%endblock%}

{% block contendbody %}

<form method="post">
    {% csrf_token %}
    <a href="#" ><button class="button special" name="Eliminar" type="submit" >Si, Eliminar</button></a>
    <a class="button" href="{% url 'users:user_list' %}">Cancelar</a>
</form>
{% endblock %}

apps/users/templates/users_form.html
{% extends 'layouts/base.html' %}

{% block title %}Crear usuario{% endblock %}
{% block bodyClass %}user{% endblock %}

{% block contendbody %}
<style>
  #id_singleLevels {
    /* height: calc(3.5rem + 2px); */
    line-height: 1.25;
    display: block;
    width: 100%;
    padding: 2.25rem 0.75rem 0.625rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #fff;
    /* color: #212529; */
    /* background-color: #fff; */
    background-clip: padding-box;
    border: 1px solid #ced4da;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border-radius: 0.25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  }

  #id_singleLevels li {
    display: block;
    min-height: 1.5rem;
    padding-left: 1.5em;
    margin-bottom: 0.125rem;
  }

  #id_singleLevels + label {
    transform: scale(.85) translateY(-0.5rem) translateX(0.15rem);
  }
</style>
<div class="user-decorator"></div>
<nav class="navbar navbar-light navbar-user">
  <div class="container">
    <a href="{% url 'users:usersList'%}" class="btn">
      <div class="d-flex">
        <span class="material-icons-round me-2">arrow_back</span> Lista de usuarios
      </div>
    </a>
    <a class="navbar-brand" href="#">
      <img src="https://www.poli.edu.co/sites/default/files/logos/logo_poli_nuevo_footer-ver5.png" alt="" height="64px">
    </a>
  </div>
</nav>
<main class="form-user mx-auto">
  <form method="post" class="card card-user mx-auto mb-5">
    {% csrf_token %}
    <div class="card-body">
      {% for field in form %}
      <div class="mb-3">
        <div class="form-floating">
          {{ field.errors }}
          {{ field }}
          {{ field.label_tag }}
        </div>
      </div>
      {% endfor %}
      {% for field in form2 %}
      <div class="mb-3">
        <div class="form-floating">
          {{ field.errors }}
          {{ field }}
          {{ field.label_tag }}
        </div>
      </div>
      {% endfor %}
    </div>

    <div class="card-footer">
      <div class="text-center">
        <button class="btn btn-lg btn-primary" type="submit">Guardar</button>
      </div>
    </div>
  </form>
</main>
{% endblock%}

{% block customJs %}
<script>
  $('#id_group').addClass('form-select');
  $('#id_password1, #id_password2').addClass('form-control');
</script>
{% endblock %}

apps/users/templates/users_list.html
{% extends 'layouts/base.html' %}

{% block title %}
Listado de usuarios del sistema
{%endblock%}

{% block contendbody %}
<style>
  thead {
    background: #0f375a;
  }

  thead th {
    color: #fff;
  }
</style>
<nav class="navbar navbar-light navbar-users">
  <div class="container">
    {% if user.is_staff %}
    <!-- <nav>
        <a href="{% url 'users:user_list'%}">listado usuarios menu</a>
      </nav> -->
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{% url 'quotes:quotesList'%}" class="nav-link">Cotizaciones</a></li>
      <li class="nav-item"><a href="{% url 'users:usersList'%}" class="nav-link active" aria-current="page">Usuarios</a></li>
    </ul>
    {% endif %}

    <!-- {% if user.get_username %}
    <h1>if logged</h1>
    {% endif %} -->

    <a class="navbar-brand" href="#">
      <img src="https://graduados.poligran.edu.co/static/img/logo-poli-vertical.png" alt="" width="156">
    </a>
  </div>
</nav>
<main>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="card card-user mx-auto">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th>Nivel de acceso</th>
                    <th>Nombre de usuario</th>
                    <!-- <th>Identificacion</th> -->
                    <th>Nombres</th>
                    <!-- <th>Apellidos</th> -->
                    <!-- <th>Correo electronico</th> -->
                    <th class="text-center">Opciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% if object_list %}
                  {% for app in object_list %}
                  <tr>
                    <th>{{app.profile.levels}}</th>
                    <td>{{app.username}}</td>
                    <!-- <td>{{app.documentation}}</td> -->
                    <td>{{app.first_name}} {{app.last_name}}</td>
                    <!-- <td>{{app.email}}</td> -->
                    <td class="text-center"><a href="{% url 'users:user_edit' app.id %}">Editar</a> /
                      <a href="{% url 'users:user_delete' app.id %}">Eliminar</a>
                    </td>
                  </tr>
                  {% endfor %}
                  {%else%}
                  <tr>
                    <td colspan="8">
                      <h1>No existen los registros de usuarios</h1>
                    </td>
                  </tr>
                  {%endif%}
                </tbody>
              </table>
            </div>
          </div>

          <div class="card-footer">
            <div class="text-end">
              <a class="btn btn-lg btn-primary" href="{% url 'users:user_create'%}">Crear usuario</a>
            </div>
          </div>
        </div>
      </div>
</main>
{% endblock %}